---
- name: Patch configuration and report collection
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - block:
        - name: Configure apt mirror
          apt_repository:
            repo: "deb http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu noble main universe"
            state: present
          register: mirror_result

        - name: Update apt cache
          apt:
            update_cache: yes
          register: update_result

        - name: Mark success
          set_fact:
            patch_report: |
              🖥️ Hostname   : {{ inventory_hostname }}
              🧠 OS         : {{ ansible_distribution }} {{ ansible_distribution_version }}
              🌐 Mirror URL : http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu
              📦 Release    : {{ ansible_distribution_release }}
              📅 Timestamp  : {{ ansible_date_time.iso8601 }}
              📁 Source     : {{ '✅ Configured' if mirror_result.changed else '✅ Already Configured' }}
              🔄 APT Cache  : {{ '✅ Refreshed' if update_result.changed else '🔄 No Updates Needed' }}
              Status       : ✅ SUCCESS
      rescue:
        - name: Mark failure
          set_fact:
            patch_report: |
              🖥️ Hostname   : {{ inventory_hostname }}
              🧠 OS         : {{ ansible_distribution }} {{ ansible_distribution_version }}
              🌐 Mirror URL : http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu
              📦 Release    : {{ ansible_distribution_release }}
              📅 Timestamp  : {{ ansible_date_time.iso8601 }}
              📁 Source     : ⚠️ Error during patch
              🔄 APT Cache  : ❌ Update Failed
              Status       : ❌ FAILED

    - name: Collect reports into localhost fact
      set_fact:
        all_reports: "{{ all_reports | default([]) + [patch_report] }}"
      delegate_to: localhost
      delegate_facts: true   # ensures persistence across plays

# -----------------------------
# Consolidation & Email
# -----------------------------
- name: Send Consolidated Email
  hosts: localhost
  gather_facts: false
  vars:
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "yourgmail@gmail.com"
    smtp_pass: "your-app-password"
    mail_to: "receiver@example.com"

  tasks:
    - name: Debug collected reports
      debug:
        var: all_reports

    - name: Count results (successful vs. failed patches)
      set_fact:
        total_hosts: "{{ all_reports | length }}"
        success_count: "{{ all_reports | select('search', '✅ SUCCESS') | list | length }}"
        failed_count: "{{ all_reports | select('search', '❌ FAILED') | list | length }}"

    - name: Send consolidated patch report via Gmail SMTP
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_pass }}"
        to: "{{ mail_to }}"
        subject: "Consolidated Patch Report"
        body: |
          ✅ Patch Summary Report ✅

          Total Hosts        : {{ total_hosts }}
          Successful Patches : {{ success_count }}
          Failed Patches     : {{ failed_count }}

          --- Host Reports ---
          {% for report in all_reports %}
          {{ report }}
          ----------------------------------------
          {% endfor %}
