---
- name: Patch configuration and report collection
  hosts: Melur
  become: true
  gather_facts: yes
  any_errors_fatal: false

  tasks:
    - name: Try to configure apt mirror and update
      block:
        - name: Configure apt mirror
          copy:
            dest: /etc/apt/sources.list
            content: |
              deb [arch=amd64 trusted=yes] http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe
              deb [arch=amd64 trusted=yes] http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-updates main universe
              deb [arch=amd64 trusted=yes] http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main universe
          register: mirror_result

        - name: Update apt cache
          apt:
            update_cache: yes
          register: update_result

        - name: Mark success
          set_fact:
            patch_report: |
              🖥️ Hostname   : {{ inventory_hostname }}
              🧠 OS         : {{ ansible_distribution }} {{ ansible_distribution_version }}
              🌐 Mirror URL : http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu
              📦 Release    : {{ ansible_distribution_release }}
              📅 Timestamp  : {{ ansible_date_time.iso8601 }}
              📁 Source     : ✅ Configured
              🔄 APT Cache  : {{ '✅ Refreshed' if update_result.changed else '🔄 No Updates Needed' }}
              Status       : ✅ SUCCESS

      rescue:
        - name: Mark failure
          set_fact:
            patch_report: |
              🖥️ Hostname   : {{ inventory_hostname }}
              🧠 OS         : {{ ansible_distribution }} {{ ansible_distribution_version }}
              🌐 Mirror URL : http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu
              📦 Release    : {{ ansible_distribution_release }}
              📅 Timestamp  : {{ ansible_date_time.iso8601 }}
              📁 Source     : ⚠️ Error during patch
              🔄 APT Cache  : ❌ Update Failed
              Status       : ❌ FAILED

    - name: Save report into host variable
      set_fact:
        single_report: "{{ patch_report }}"

    - name: Collect results into localhost variable
      set_fact:
        all_reports: "{{ all_reports | default([]) + [ hostvars[item].single_report ] }}"
      delegate_to: localhost
      run_once: true
      with_items: "{{ ansible_play_hosts }}"

# -----------------------------
# Send ONE consolidated email
# -----------------------------
- name: Send Consolidated Email
  hosts: localhost
  gather_facts: false
  vars:
    notification_recipients: "receiver@example.com"
    report_time: "{{ lookup('pipe','date +%Y-%m-%dT%H:%M:%S') }}"
    total_hosts: "{{ groups['all'] | length }}"

  tasks:
    - name: Debug collected reports
      debug:
        var: all_reports

    - name: Count results
      set_fact:
        successful_patches: "{{ all_reports | select('search', '✅ SUCCESS') | list | length }}"
        failed_patches: "{{ all_reports | select('search', '❌ FAILED') | list | length }}"

    - name: Send consolidated patch report via Gmail SMTP
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        secure: starttls
        username: "{{ lookup('env', 'EMAIL_USER') }}"
        password: "{{ lookup('env', 'EMAIL_PASSWORD') }}"
        to: "{{ notification_recipients }}"
        from: "{{ lookup('env', 'EMAIL_USER') }}"
        subject: "Mirror Patch Report - {{ report_time }}"
        subtype: plain
        body: |
          Hello Team,

          ✅ Patch Summary Report ✅

          Total Hosts        : {{ total_hosts }}
          Successful Patches : {{ successful_patches }}
          Failed Patches     : {{ failed_patches }}

          --- Host Reports ---
          {% for report in all_reports %}
          {{ report }}
          ----------------------------------------
          {% endfor %}

          Regards,
          🔧 Ansible Automation System
