---
- name: Configure APT Mirror on all hosts
  hosts: Melur
  become: false
  vars:
    mirror_url: "http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu"
    release: "noble"
    is_kali: "{{ ansible_distribution == 'Kali' }}"

    # Sources for Kali
    sources_content_kali: |
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }} main universe
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-updates main universe
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-security main universe

    # Sources for Mint/Ubuntu
    sources_content_mint: |
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }} main universe
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-updates main universe
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-security main universe

  tasks:
    - name: Patch block
      block:
        - name: Update sources.list with local mirror
          become: yes
          copy:
            dest: /etc/apt/sources.list
            content: "{{ sources_content_kali if is_kali else sources_content_mint }}"
          register: sources_result

        - name: Update APT package cache
          become: yes
          apt:
            update_cache: yes
          register: apt_result

        - name: Mark patch success
          set_fact:
            patch_status: "SUCCESS"
            sources_file_status: "✅ Updated"
            apt_cache_status: "✅ Refreshed"
      rescue:
        - name: Mark patch failed
          set_fact:
            patch_status: "FAILED"
            sources_file_status: "❌ Failed"
            apt_cache_status: "❌ Failed"
      always:
        - name: Export results to controller
          delegate_to: localhost
          run_once: false
          set_fact:
            patch_results: "{{ (patch_results | default([])) + [ {
                'host': inventory_hostname,
                'status': patch_status,
                'os': ansible_distribution ~ ' ' ~ ansible_distribution_version,
                'mirror': mirror_url,
                'release': release,
                'timestamp': ansible_date_time.iso8601,
                'sources_file_status': sources_file_status,
                'apt_cache_status': apt_cache_status
              } ] }}"

# ==================== SECOND PLAY ====================

- name: Send consolidated email report
  hosts: localhost
  gather_facts: true
  vars:
    notification_recipients: "aravind_slcs_intern2@aravind.org,karthikeyan.sudhakar@aravind.org"

  tasks:
    - name: Ensure patch_results is defined
      set_fact:
        patch_results: "{{ patch_results | default([]) }}"

    - name: Separate success and failure hosts
      set_fact:
        success_hosts: "{{ patch_results | selectattr('status','equalto','SUCCESS') | list }}"
        failed_hosts: "{{ patch_results | selectattr('status','equalto','FAILED') | list }}"

    - name: Send summary email with details
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        secure: starttls
        username: "{{ lookup('env', 'EMAIL_USER') }}"
        password: "{{ lookup('env', 'EMAIL_PASSWORD') }}"
        to: "{{ notification_recipients }}"
        from: "{{ lookup('env', 'EMAIL_USER') }}"
        subject: "Mirror Patch Report - {{ ansible_date_time.iso8601 }}"
        body: |
          Hello Team,

          ✅ Patch Summary Report ✅

          Total Hosts       : {{ patch_results | length }}
          Successful Patches: {{ success_hosts | length }}
          Failed Patches    : {{ failed_hosts | length }}

          --- Success Hosts ---
          {% for h in success_hosts %}
          Hostname   : {{ h.host }}
          OS         : {{ h.os }}
          Mirror URL : {{ h.mirror }}
          Release    : {{ h.release }}
          Timestamp  : {{ h.timestamp }}
          Source List File : {{ h.sources_file_status }}
          APT Cache Status : {{ h.apt_cache_status }}

          {% endfor %}

          --- Failed Hosts ---
          {% for h in failed_hosts %}
          Hostname   : {{ h.host }}
          OS         : {{ h.os }}
          Mirror URL : {{ h.mirror }}
          Release    : {{ h.release }}
          Timestamp  : {{ h.timestamp }}
          Source List File : {{ h.sources_file_status }}
          APT Cache Status : {{ h.apt_cache_status }}

          {% endfor %}

          Regards,
          🔧 Ansible Automation System
