---
- name: Configure APT Mirror and Send Notification
  hosts: all
  become: yes
  vars:
    mirror_url: "http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu"
    release: "noble"
    is_kali: "{{ ansible_distribution == 'Kali' }}"
    sources_content_kali: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }} main restricted universe multiverse
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }}-updates main restricted universe multiverse
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }}-security main restricted universe multiverse
    sources_content_mint: |
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }} main restricted universe multiverse
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-updates main restricted universe multiverse
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-security main restricted universe multiverse

  tasks:
    - name: Update sources.list with local mirror
      copy:
        dest: /etc/apt/sources.list
        content: "{{ sources_content_kali if is_kali else sources_content_mint }}"
      register: apt_result

    - name: Update APT package cache
      apt:
        update_cache: yes
      when: apt_result is changed

    - name: Send notification email
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: "aravind_slcs_intern2@aravind.org"
        password: "hjcqlojjlcatjwqq"
        to: "aravind_slcs_intern2@aravind.org"
        from: "aravind_slcs_intern2@aravind.org"
        subject: "📦 Mirror Patch Success on {{ inventory_hostname }}"
        body: |
          Hello Team,

          ✅ The system **{{ inventory_hostname }}** has successfully patched packages from the local mirror repository.

          🖥️ Hostname         : {{ inventory_hostname }}
          🧠 Operating System : {{ ansible_distribution }} {{ ansible_distribution_version }}
          🌐 Mirror URL       : {{ mirror_url }}
          📦 Release          : {{ release }}
          📅 Timestamp        : {{ ansible_date_time.iso8601 }}

          📌 Source list applied:
          {{ (sources_content_kali if is_kali else sources_content_mint) | indent(2) }}

          Regards,  
          🔧 Ansible Automation System
      when: apt_result is succeeded
      delegate_to: localhost
