---
- name: Configure APT Mirror and Send Consolidated Notification
  hosts: Melur
  become: yes
  vars:
    mirror_url: "http://172.17.9.58/Ubuntu/mirror/archive.ubuntu.com/ubuntu"
    release: "noble"
    is_kali: "{{ ansible_distribution == 'Kali' }}"

    # Sources for Kali
    sources_content_kali: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }} main universe
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }}-updates main universe
      deb [arch=amd64 signed-by=/etc/apt/keyrings/ubuntu.gpg] {{ mirror_url }} {{ release }}-security main universe

    # Sources for Mint/Ubuntu
    sources_content_mint: |
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }} main universe
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-updates main universe
      deb [arch=amd64 trusted=yes] {{ mirror_url }} {{ release }}-security main universe

    # Multiple recipients
    notification_recipients: "aravind_slcs_intern2@aravind.org,karthikeyan.sudhakar@aravind.org"

  tasks:
    - name: Patch Block
      block:
        - name: Update sources.list with local mirror
          copy:
            dest: /etc/apt/sources.list
            content: "{{ sources_content_kali if is_kali else sources_content_mint }}"
          register: sources_result

        - name: Update APT package cache
          apt:
            update_cache: yes
          register: apt_result

        - name: Mark status SUCCESS or UP-TO-DATE
          set_fact:
            patch_status: >-
              {% if apt_result.changed or sources_result.changed %}
              ✅ SUCCESS
              {% else %}
              🔄 UP-TO-DATE
              {% endif %}

      rescue:
        - name: Mark status FAILED
          set_fact:
            patch_status: "❌ FAILED"

    - name: Save patch status into hostvars
      set_fact:
        patch_summary:
          status: "{{ patch_status }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Build consolidated results table (run once)
      run_once: true
      delegate_to: localhost
      set_fact:
        consolidated_report: |
          | Hostname/IP | Status | OS |
          |-------------|--------|----|
          {% for host in groups['linux_servers'] %}
          | {{ host }} | {{ hostvars[host].patch_summary.status }} | {{ hostvars[host].patch_summary.os }} |
          {% endfor %}

    - name: Send consolidated notification email
      run_once: true
      delegate_to: localhost
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        secure: starttls
        username: "{{ lookup('env', 'EMAIL_USER') }}"
        password: "{{ lookup('env', 'EMAIL_PASSWORD') }}"
        to: "{{ notification_recipients }}"
        from: "{{ lookup('env', 'EMAIL_USER') }}"
        subject: "📢 Mirror Patch Report - Linux Servers"
        body: |
          Hello Team,

          The patch update operation has been completed for the server group **linux_servers**.

          {{ consolidated_report }}

          Regards,  
          🔧 Ansible Automation System
